# Generated by Django 4.0.5 on 2022-06-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='date_hired',
            new_name='date_onboarded',
        ),
    ]
