# Generated by Django 4.0.5 on 2022-07-15 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_rename_date_hired_seller_date_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='date_expired',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
